import axios from 'axios';
import {validatePassword} from './controllers/aux/auth_helper';
var jwt = require('jsonwebtoken');
var _ = require('lodash');
var nodemailer = require('nodemailer');
import Database from './database';
import User from './models/user';
var bcrypt = require('bcrypt');
const saltRounds = 6;
